### ISSUE TITLE
Missing Important Baseline: Motion Avatar

### ISSUE THREAD

**Issue by zzh666123321** [haoz19/MagicPose4D#2]

**Comment by haoz19** [comment]
First of all, this is not OpenReview, so I don’t feel obligated to spend time rebutting your points. However, I am still willing to kindly address your concerns. 

The work you mentioned, Motion Avatar, was accepted in July 2024 and was first posted on arXiv on May 18, 2024. To date, no code has been released. It’s worth noting that MagicPose4D was released on arXiv just four days later, on May 22, 2024. So, I ask you, do you not consider two works released just four days apart as contemporaneous? And how do you even compare a project that hasn’t released its code yet?

Furthermore, you claim that the techniques in both works are very similar. I am quite certain you haven’t thoroughly read either paper. The logic behind the two is entirely different—one follows a feedforward approach, while the other is optimization-based.

Third, I do not believe that MagicPose4D performs worse than Motion Avatar, especially in terms of motion control. 

Finally, I welcome constructive feedback and discussion, but if your only intent is to **troll** or act as **“a keyboard warrior”**, I would kindly ask you not to hide behind an anonymous account just to ruin someone else’s day.
